### ISSUE TITLE
SUKTS breaks by adding all tracks in minimal settings

### ISSUE THREAD

**Issue by kevinfields777** [StarRaid/Standardised-UK-Track-Set#3]
Using a mix of track sets and train sets that add tracks, I've found a novel way to break SUKTS. Using the included save game with settings, and with SUKTS set to minimal tracks setting, I should have 39 tracks enabled. Instead, SUKTS malfunctions, enables all track types, and then exceeds the 64 railtype limit.  Client is JGRPP 0.51.1  
[SUKTS-Broken-2023-03-05.zip](https://github.com/StarRaid/Standardised-UK-Track-Set/files/10890879/SUKTS-Broken-2023-03-05.zip)

**Comment by StarRaid** [comment]
Tested with the release I made today and it seems to fixed now. I'd advise loading it after the railtype compatibility GRF until I update that too, as it has outdated definitions that will override this SUKTS update.

**Comment by Brickblock1** [comment]
The definitions only add they don't override this also seems to have broken metro tracks in non extra selaction choices
